version: '3.8'

services:
  frontend:
    build: ./frontend
    image: dakshkhungla/mysql_to_nosql_frontend:${BUILD_NUMBER}
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: dakshkhungla/mysql_to_nosql_backend:${BUILD_NUMBER}
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
